### ISSUE TITLE
Test Seeding Input Data Defaults

### ISSUE THREAD

**Issue by braughtg** [DickinsonCollege/FD2School-FarmData2#155]
The tests created for this issue will test the default contents of the "Data" section of the Seeding Input Form in the FieldKit.

These tests must check that the Data section of the Seeding Input Form:
- [x] - has the header "Data"
- [x] - the date input element is enabled
- [x] - the date input element has the default value of the current date
- [x] - the crop drop down is enabled
- [ ] - the crop drop down does not have a selected value
- [x] - the crop drop down contains the correct crop list

Other information:
 - The source code and tests for the Seeding Input Form will be in the `farmdata2/farmdata2_modules/fd2_field_kit/seedingInput` directory.
 - The `seedingInput.html` file contains the source code for the page.
 - The tests for this issue should be created in a new file named `seedingInput.data.defaults.spec.js`
 - The above tests should be broken up into logically organized `it` blocks within the test file.

**Comment by braughtg** [comment]
Some additional notes:
  - It is not necessary to include a separate `it` for each of the things to be tested.
  - You should decide how to divide the things being tested into `it`s so that each `it` tests a cohesive set of things.
  - The message for each `it` should describe in a short phrase what the `it` is testing.
  - The `.spec.js` file should include a comment at the top that describes what the file as a whole is testing.
  - The message for the `describe` should describe in a short phrase what the file is testing.
  - **The `.spec.js` files in the `farmdata2/farmdata2_modules/fd2_example/` sub-tabs (e.g. `ui`, `api`) may provide some helpful examples.**

**Comment by infantlikesprogramming** [comment]
I am writing to address a difficulty that I am having when checking if the crop has a selected value at the beginning in seedingInput.html. Specifically, I was working on checking if the element dropdown-with-all (data-cy="crop-selection") already has a selected value.  I was not able to obtain the selected value of the element, so my approach was to loop through all options of the select element (in the dropdown-with-all element). However, my code does not seem to execute right because it could not find the value of the length of the crop list. Can anybody suggest a different approach or spot where my code has gone wrong? Thank you for your attention.

Note: If I initialize i with an int (110 for example), then the code still works and checks to see if any crop has been selected yet.

Code: 
```javascript
let i = cy.get("[data-cy=crop-selection] > [data-cy=dropdown-input]").children().its('length')
i.should('equal',111)
for (i; i>0; i--){
     cy.get("[data-cy=crop-selection] > [data-cy=dropdown-input]").children().eq(i-1).should("not.be.selected")
}
```

**Comment by braughtg** [comment]
> I am writing to address a difficulty that I am having when checking if the crop has a selected value at the beginning in seedingInput.html.

I think you may be over complicating the task here.  The test for this issue should ensure that the dropdown **does not** have any value selected when the page loads.  That is the drop down should be empty as shown here:

![image](https://user-images.githubusercontent.com/16962482/230156011-c6bd41ab-a7a5-4f49-9e9b-10bf186ae63d.png)

Does that help to clarify?

**Comment by Mikek16** [comment]
i would like to work on this issue.

**Comment by infantlikesprogramming** [comment]
@braughtg Thank you for your response. I have tried the approach where I try to find the selected option element and test whether it has the empty string in its text. However, the test returns a very confusing message where it says that the element should have text '', but the text was ''. Can you please take a look and see if I have accessed the selected option of the select element, and if I did, why did the error message pop up (because the selected element do have text '')? 

Here's my code:
```javascript
it("Checks if any crop-dropdown option has been selected ", ()=>{
        cy.get("[data-cy=crop-selection] > [data-cy=dropdown-input]").find('option:selected').should('have.text', '')
}) 
```
Here's a picture of the test's message:
<img width="287" alt="Screen Shot 2023-04-07 at 12 42 57 PM" src="https://user-images.githubusercontent.com/60119105/230645654-f0f019c8-d3f7-45b0-8336-5d98966a33de.png">

**Comment by braughtg** [comment]
@infantlikesprogramming 

> I have tried the approach where I try to find the selected option element and test whether it has the empty string in its text.

I think there are three issues here.  

First, you want to check the value of the `dropdown-input` (i.e. what is selected) not the text that is in the `dropdown-input`.  To check the value you'll need to use `has.value` instead of `has-text` in your `should` assertion.

Second, I believe that the value of the dropdown will probably be `null` (rather than `""`) when the page is loaded and no crop has been selected.  You can confirm that when you run your test.

Third, there is a technical issue that comes up with this test because it relies on information that is being retrieved from the database via an API call.  Recall that the list of crops is populated via an API call that is made in the Vue.js `created` hook.  So, we should wait until the list of crops has been populated before running this particular test.  You can do that by adding the following line at the start of your `it`:
```
   cy.waitForPage()
``` 
This call will wait until the page has been fully loaded, including all of the API calls that are made in the `created` hook.  Once that has happened, then your test will continue and should check the value of the dropdown.

**Comment by infantlikesprogramming** [comment]
@braughtg I have followed your advice and have successfully solved the problem. Thank you so much for your help!
